### ISSUE TITLE
Memory managment of serialization lib on javascript

### ISSUE THREAD

**Issue by AngelCastilloB** [dcSpark/cardano-multiplatform-lib#142]
Hi, I am currently trying to implement proper memory management and disposal of the CML objects in the projects I have that use this library, but I would like to understand how far I need to go to properly dispose of all the objects, do I need to call free on every object that I create using one of the constructors, or is it enough to free the parent object?, for example, when creating a transaction we need to provide all sort of objects (redeemers, datums, signatures, input, outputs etc), is it enough to free the transaction where these objects have been added to it or we must free all of the objects individually? The same question goes for objects we get from other objects, do we need to manually free all these objects returned by the getters, or is it enough to free the parent object?.

**Comment by rooooooooob** [comment]
>I would like to understand how far I need to go to properly dispose of all the objects, do I need to call free on every object that I create using one of the constructors, or is it enough to free the parent object?
 
AFAIK every wasm struct (e.g. not primitives that wasm_bindgen converts) passed to constructors are done by reference then cloned to avoid nasty issues/crashes like accessing a variable that would get moved out (and thus deallocated) after it's passed in. So you'll need to free those parameters as well if you want to avoid memory leaks.

>The same question goes for objects we get from other objects, do we need to manually free all these objects returned by the getters, or is it enough to free the parent object?.

AFAIK every getter should return a cloned version to avoid nasty accessing freed memory issues, so you'll want to call free() on those too.

It's a bit of a shame that this needs to be done, but it's hard to avoid when using wasm_bindgen since rust and javascript have such fundamentally different ways of memory management (RAII vs GC) which don't play well together. And the alternative of returning references/taking in parameters by value leads to easy accidental accessing of freed memory in a way that can't be nicely checked against at compile time like when using from rust, so that's why we went with the clone-happy approach.

**Comment by rooooooooob** [comment]
>The ipv4 object is being cloned. so is this a forced memory leak in this particular case? 

What happens in the other cases is we take it by reference, so it isn't moved into the function in rust (leading to it being freed in wasm), so we *need* to clone it. Here it's being moved into the function, and I believe that clone is actually not necessary for `Option<T>`. There shouldn't be a leak unless there's an issue with `wasm_bindgen` in how it implements the to/from wasm traits for `Option<T>` where `T` implements those traits.
