### ISSUE TITLE
Advice for depending on the CML starting tomorrow

### ISSUE THREAD

**Issue by waalge** [dcSpark/cardano-multiplatform-lib#184]
I've stared at this repo for a while now, and I think I've just about got the gist of what belongs to the "old" and to the "new" versions of CML. 

If I were to start a project tomorrow depending on the CML, would you advise depending on `./rust` and migrating in due time, 
or going straight to using the new crates?
I appreciate the answer is likely "ummm. Depends on your use case" and it more an invitation to any signposting on:

- what the architecture roadmap is
- something akin to ADRs that motivated these
- how painful a migration would be

This would be super helpful. 

I spoke a little to txpipe people, trying to ascertain a comparison between aspects of pallas and CML, 
and whether that would be a more stable dependency for a project-starting-tomorrow. 

Many thanks

---

This Q is an abuse of the gh issues, and you may close it as you see fit - no hard feelings.

**Comment by SebastienGllmt** [comment]
The new code isn't in any package at the moment (except for CIP25), so it may be a bit tedious to use.

If your goal is to write a project that has its own custom binary format (new tx metadata standard, new Plutus datum format, etc.) and you'd like to code generate it, the CML option might work best so that it's all based on the same primitives (same way the cip25 crate reuses the CML metadatum definitions)

If that's not something you need, then it's up to you which you pick. If CML sounds like a cool project to you in general, you're more than welcome to help contribute as we're near the end of generating the new architecture and will soon have to move into documentation and adding utility functions

**Comment by waalge** [comment]
I was attempting to write some informed follow up, but there's a lot I'm still unpicking... 

Ok I see that for cip25 there is a `./spec/cip25.cddl` and then there's a top level `./cip25/` with a rust a wasm subdir. 
And would assume that, bar the `utils.rs` file, this is the unadulterated output of 
```
cddl-codegen --input ./spec/cip25.cddl --output ./cip25
```
Although, just inspecting the `tree` I get an additional `errors.rs` file.... hmmm. 
(An aside: is it possibly helpful to see which version of the cddl-codegen generated the code?) 

I can't see the code in `./cip25` used here, or anywhere else, yet. 
I'm guessing the intended dev workflow for a dapp is something like:

- write a cddl with data types. 
- generate rust and wasm libs
- add utils/ helpers 
- write a lib of tx-builders - this will depend on the above and the CML 

How off-course does this sound?

---

Aiken allows for computation of script costs from within rust and not depending on an external service - helpful.
But its a bit strange to now have a process where there are two distinct sets of libs providing serialization: CML and pallas*.

Have I understood this correctly/ Is this strange?

Many thanks,

**Comment by SebastienGllmt** [comment]
> Have I understood this correctly

Yes, sounds right

> But its a bit strange to now have a process where there are two distinct sets of libs providing serialization: CML and pallas*.

CML has been a project that has spanned multiple years since building this whole codegen pipeline is time-consuming as you can imagine. When Pallas was created, CML didn't support native Rust output (only WASM), which made the Rust interface ugly to work with. Pallas was created to bypass this old limitation of CML which doesn't exist with the new system anymore
