### ISSUE TITLE
Create CI checks for refactored CML

### ISSUE THREAD

**Issue by gostkin** [dcSpark/cardano-multiplatform-lib#230]
the checks should verify the format, clippy warnings and run tests

**Comment by rooooooooob** [comment]
Regarding warnings, what should we do about the old code we brought over from IOHK's legacy chain-libs? We have it in `crypto`'s `chain_core` / `chain_crypto` / `impl_lockchain` / `typed_bytes`. There are a bunch of unused warnings since we don't pub export the modules as they're mostly dependencies we use for our crypto code to work.

Should we pub export it? Pros: Maybe useful to someone? Easiest way to get rid of those errors. Cons: Could confuse users with all those types.

Or delete/rename to _* all the unused functions / types?

Or put a clippy ignore in those mods? (also would be super easy and wouldn't add to our public API). I"m leaning to this at least for now as it's easy to undo if we change our minds and doesn't change the API at all and we generally never touch the code in those modules (more like included deps) anyway.

**Comment by rooooooooob** [comment]
Fixed by #250
