### ISSUE TITLE
Missing WASM TransactionUnspentOutputs export?

### ISSUE THREAD

**Issue by solidsnakedev** [dcSpark/cardano-multiplatform-lib#294]
it looks like `TransactionUnspentOutputs` class is missing, this was already in version 3.1.2

**Comment by rooooooooob** [comment]
@solidsnakedev What is the use case for it? For WASM bindings when we need to expose an array of `Foo` we would create a `Foos` (now it would be called `FooList`) struct like the one here. It was just to get around the wasm_bindgen limitation of not being able to directly export `Vec<TransactionUnspentOutput>`. I can't see anywhere in the API that would require an array of `TransactionUnspentOutput` anymore so that's why it's not there.

I am looking at the old codebase too and I see the struct but I don't see any API that uses it. Likely it was used at some point then that API was removed or changed but the array wrapper was never removed. You could just use an array of `TransactionUnspentOutput` instead or is there a specific need for it now? I thought maybe CIP30 but those seem to be JS arrays around each `TransactionUnspentOutput`.

**Comment by solidsnakedev** [comment]
The only place I've seen this is in Lucid which is a CML wrapper, as reference https://github.com/spacebudz/lucid/blob/457c156e74ef49ce35823aa2bca91b3bbc585221/src/lucid/lucid.ts#L251
@rooooooooob 
It's also available here line -> line `23267` https://www.npmjs.com/package/@dcspark/cardano-multiplatform-lib-nodejs/v/3.1.2?activeTab=code

Thanks for your suggestion, but is it ok to make an array of `TransactionUnspentOutput` in terms of efficiency?

**Comment by solidsnakedev** [comment]
I'm using `Array<CML.TransactionUnspentOutput>`, I think I can close this, thank you

**Comment by rooooooooob** [comment]
For efficiency I don't think it would be worse since any accessing of the `TransactionUnspentOutputs` would require going to/form the rust/wasm <-> js boundary anyway (e.g. `.get()`). You could potentially have it be more efficient if it's passed in to some other wasm/rust API like `fn do_something_with_inputs(inputs: &TransactionUnspentOutputs)` but we don't have anything that use it so I don't think it's an issue.
